name: Android APK (Capacitor)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm ci

      # Génère/synchronise le projet Capacitor (utilise les scripts de ton package.json)
      - name: Init & sync Capacitor
        run: |
          npm run cap:init
          npm run cap:add:android
          npm run cap:sync

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # >>> La ligne importante : accepte les licences + installe SDK & build-tools
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: "34.0.0"
          accept-licenses: true

      - name: Build debug APK
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: stopaddict-debug-apk
          path: android/app/build/outputs/apk/debug/*.apk
